### ISSUE TITLE
Add two additional links to initial log-in popup

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/CODAP#11]
1) About (links to the About section)
2) Terms (links to the term section)

Bruno, it would be great if you can complete this by June 13th, but no worries if you cannot. If I have time this weekend, I may add the links from my personal computer.

** This will need to be done for both the English and French version **

![picture1](https://user-images.githubusercontent.com/19412148/26984328-f5ffd7ae-4d0c-11e7-84a9-853fbb42709b.png)

**Comment by staubibr** [comment]
Did you try to add them over the weekend? It's not as easy as it seems because the About and Terms sections are not other web pages. They're just HTML elements that have to be opened through javascript. You need to wire events across views. I have some time right now, I'll have a look, maybe I can get it done in a short time.

**Comment by staubibr** [comment]
I added the links to the login popup.
