### ISSUE TITLE
French section bug

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/CODAP#5]
![osm](https://cloud.githubusercontent.com/assets/19412148/25964091/aba629d2-3651-11e7-951b-e1a63c3280d8.PNG)

**Comment by staubibr** [comment]
This was a semi intentional bug. It was happening because I intentionally left the localized strings empty for the french version of the license popup. But it shouldn't have crashed like it was doing, It should've just shown an empty license popup in the french version. 

Anyways, it's fixed now but the license popup will look weird until we include the french version of the license
